---
- name: Prepare all k3s cluster nodes
  hosts: servers
  become: true
  roles:
    - k3s-common

- name: Initialize first k3s server
  hosts: servers[0]
  become: true
  vars:
    k3s_mode: init
  roles:
    - k3s-server

- name: Deploy kube-vip control plane VIP
  hosts: servers[0]
  become: true
  roles:
    - kube-vip

- name: Join additional k3s servers
  hosts: servers[1:]
  serial: 1
  become: true
  vars:
    k3s_mode: join
  roles:
    - k3s-server